# Reference: https://github.com/i3/i3/blob/next/etc/config

start-at-login = true

gaps.inner.horizontal = 8
gaps.inner.vertical = 8

gaps.outer.left = 8
gaps.outer.bottom = 8
gaps.outer.top = 8
gaps.outer.right = 8

accordion-padding = 8

# enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-enter = 'exec-and-forget open -n /Applications/Kitty.app'

alt-h = 'focus left'
alt-n = 'focus right'
alt-t = 'focus down'
alt-c = 'focus up'

alt-shift-h = 'move-through left'
alt-shift-n = 'move-through right'
alt-shift-t = 'move-through down'
alt-shift-c = 'move-through up'

# Use SKHD for this.
# alt-shift-pipe = 'split horizontal'
# alt-shift-underscore = 'split vertical'

alt-shift-f = 'fullscreen'

alt-f = 'layout v_accordion' # 'layout stacking' in i3
alt-d = 'layout h_accordion' # 'layout tabbed' in i3
alt-b = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide.html#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'

# Join
alt-shift-semicolon = 'mode join'
# Resize
alt-r = 'mode resize'

[mode.join.binding]
c = 'join-with up'
h = 'join-with left'
n = 'join-with right'
t = 'join-with down'
enter = 'mode main'
esc = 'mode main'

[mode.resize.binding]
c = 'resize width +50'
h = 'resize width -50'
n = 'resize height +50'
t = 'resize height -50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'pl.maketheweb.cleanshotx'
run = 'layout floating'

# Start all windows in floating mode.
#[[on-window-detected]]
#run = 'layout floating'
